### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by Xoronic** [evenorog/redo#6]
Hi! I stumbled upon this library and it really looks a lot like this library 'Actions' I've written: https://github.com/actions-library/actions .

I see that your crate is a lot older and I don't really know for certain how I did not notice this library. If I did, I would have never written mine. I'm not sure if concepts like merging were inspired by my library or that we both came up with the same ideas.. In both cases I think it is pretty cool :)

Anyway, if you want to talk about the design of the API or if you need any other help regarding the library, please let me know!

EDIT: Could you please explain your choice for implementing the logic on the command and not on the state? I personally experienced that Rust made that awkward to do with lifetimes. How did you get around that?

EDIT 2: I guess I found the answer to the question above myself :) Implementing on the commands keeps the logic nicely separated.

**Comment by evenorog** [comment]
Hi! Yes I believe [this](https://github.com/evenorog/redo/commit/362f7f24f5fc8e5d42bc7c5eecd4cad66d45ebfc) commit in particular is inspired by your library (before, merge just returned a Result). Initially, this library was based on Qt's undo-redo framework but it has changed quite a bit since then.

I'm trying to get this library and [undo](https://github.com/evenorog/undo) to a `1.0.0` release so if you have any ideas or thoughts about the API I would love to hear it! When rust get const generics I'm planning to have a `no_std` variant of `Record`, but other than that I don't have any plans for new features for now.

**Comment by Xoronic** [comment]
Hmm, about the naming.. Are you planning on keeping that naming for `1.0.0`? I think having two libraries "undo" and "redo" can really be really confusing (it confused me at least :) ).

I think it would be a good idea to mention the counterparts in a prominent place somewhere in both the `README`s.

Have you considered combining the libraries or giving them more distinct names? Or am I missing something?

**Comment by evenorog** [comment]
Yes, I don't want to rename the libraries, but I need to add a comparison to the `README` and the docs that explains the differences between them and when you want to use one or the other (think I had that at some point but it got removed), before the release! 

Since the `Command` trait is different in the two libraries and everything builds on that, there is not much code that can be shared and the user will most likely never use both libraries at the same time anyway so I don't think I'm going to try to combine them.
